---
abstract: 'Modules AMD uses'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-AMD
requires:
  App::Ack: 0
  App::Cmd: 0
  App::Nopaste: 0
  App::Software::License: 0
  App::cpanminus: 0
  Bundle::CPAN: 0
  Bundle::LWP: 0
  Bundle::libnet: 0
  CPAN::Mini: 0
  CPAN::Mini::Devel: 0
  CPAN::Uploader: 0
  Cache::Cache: 0
  Cache::FileCache: 0
  Carp::Always: 0
  Carp::Always::Color: 0
  Carp::REPL: 0
  DBD::SQLite: 0
  DBD::mysql: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Class::Schema::Versioned: 0
  DBIx::Class::TimeStamp: 0
  Data::DPath: 0
  Data::Visitor: 0
  Data::YAML: 0
  DateTime: 0
  DateTime::Format::Builder: 0
  DateTime::Format::Mail: 0
  DateTime::Format::MySQL: 0
  DateTime::Format::Natural: 0
  DateTime::Format::Strptime: 0
  Devel::Backtrace: 0
  Devel::Cover: 0
  Devel::NYTProf: 0
  Devel::bt: 0
  Digest::SHA1: 0
  Directory::Scratch: 0
  Dist::Zilla: 0
  Dist::Zilla::App::Command::weaverconf: 0
  Dist::Zilla::PluginBundle::AMD: 0
  File::ShareDir: 0
  File::Slurp: 0
  File::Type: 0
  Function::Parameters: 0
  Hash::Merge: 0
  Hash::Merge::Simple: 0
  JSON: 0
  JSON::Syck: 0
  JSON::XS: 0
  List::AllUtils: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  MIME::Lite: 0
  MIME::Tools: 0
  MIME::Types: 0
  Method::Signatures: 0
  Method::Signatures::Simple: 0
  Module::Install: 0
  Module::Install::AuthorRequires: 0
  Module::Install::AuthorTests: 0
  Module::Install::CheckConflicts: 0
  Module::Install::ExtraTests: 0
  Module::Starter: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::Daemonize: 0
  MooseX::Declare: 0
  MooseX::LazyRequire: 0
  MooseX::Log::Log4perl: 0
  MooseX::Method::Signatures: 0
  MooseX::Types::Common: 0
  MooseX::Types::DateTime: 0
  MooseX::Types::Email: 0
  MooseX::Types::LoadableClass: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  Net::Daemon: 0
  Net::SSH: 0
  Net::SSH::Expect: 0
  Net::Server: 0
  Net::Server::PreForkSimple: 0
  Net::TFTP: 0
  Parse::RecDescent: 0
  Perl::Version: 1.010
  Pod::Coverage::TrustPod: 0
  Regexp::Common: 0
  SQL::Translator: 0
  String::Diff: 0
  Sub::Exporter: 0
  TAP::DOM: 0
  TAP::Formatter::HTML: 0
  TAP::Parser::Aggregator: 0
  Task::Catalyst: 0
  Task::SDK::Moose: 0
  Template: 0
  Term::ReadLine::Gnu: 0
  Term::ReadLine::Perl: 0
  Test::Aggregate: 0
  Test::Deep: 0
  Test::Fixture::DBIC::Schema: 0
  Test::MockModule: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::WWW::Mechanize::Catalyst: 0
  Test::Without::Module: 0
  TryCatch: 0
  URI: 0
  URI::Escape: 0
  V: 0
  XML::Generator: 0
  XML::Simple: 0
  YAML: 0
  YAML::Syck: 0
  YAML::XS: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-AMD
  homepage: http://metacpan.org/release/Task-BeLike-AMD
  repository: git://github.com/amd/Task-BeLike-AMD.git
version: 0.002
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@AMD/GatherDir'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@AMD/PruneCruft'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@AMD/ManifestSkip'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@AMD/MetaYAML'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@AMD/Readme'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@AMD/ExtraTests'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@AMD/ExecDir'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@AMD/ShareDir'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@AMD/MakeMaker'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@AMD/Manifest'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@AMD/TestRelease'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@AMD/ConfirmRelease'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@AMD/UploadToCPAN'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@AMD/MetaConfig'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@AMD/MetaJSON'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@AMD/PkgVersion'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@AMD/PodSyntaxTests'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@AMD/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@AMD/PodCoverageTests'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@AMD/MetaResources'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@AMD/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@AMD/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@AMD/TaskWeaver'
      version: 0.101624
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@AMD/AutoPrereqs'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@AMD/CheckChangesHasContent'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@AMD/NextRelease'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@AMD/Git::CheckFor::CorrectBranch'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@AMD/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@AMD/@Git/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@AMD/@Git/Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@AMD/@Git/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@AMD/@Git/Push'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300016
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300016
x_authority: cpan:AMD
